name: Update Blacklist
on:
  push:
    paths-ignore:
    - '.github/**'
    - 'lists/**'
    - '*.txt'
    - '*.yaml'
    - '*.conf'
    - '*.txt'
    - '*.sh'
    - '*.py'
    - 'README.md'
  schedule:
    - cron: '30 7 * * *'

jobs:
  build-blocklist:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Build blocklist
        uses: actions/checkout@v3
      - run: |
          sudo python3 generate-domains-blocklist.py --allowlist domains-allowlist.txt > blocklist.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update blacklist"
          git push
