name: Update Whitelist

       # Controls when the workflow will run
on:
  repository_dispatch:
  workflow_dispatch:
  push:
    paths-ignore:
    - '.github/**'
    - 'lists/**'
    - '*.txt'
    - '*.yaml'
    - '*.conf'
    - '*.txt'
    - '*.sh'
    - '*.py'
    - 'README.md'
  schedule:
    - cron: "15 7 * * *"

     # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Build blocklist
        uses: actions/checkout@v2
      - run: |
          sudo python2 generate-domains-whitelist.py > domains-allowlist.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update whitelist"
          git push
